#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
blockMesh
touch drop.foam

if [ "$1" = "Coarse" ]; then
    setFields
else
    for i in {1..3}
    do
        VOFSetFields
        initDynamicMesh
    done

    VOFSetFields
fi;

interDyMFoam

# ----------------------------------------------------------------- end-of-file
