#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso geometryTools
wmake initDynamicMesh
wmake VOFSetFields

# ----------------------------------------------------------------- end-of-file
