#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso geometryTools
wclean initDynamicMesh
wclean VOFSetFields

# ----------------------------------------------------------------- end-of-file
